version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: patient_db
    environment:
      POSTGRES_DB: patient_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: patient_app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=patient_management
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - database

volumes:
  postgres_data: